### ISSUE TITLE
Django model utils issue on devstack

### ISSUE THREAD

**Issue by OmarIthawi** [appsembler/devstack#50]
**Problem:** Devstack breaks and throws a `TypeError` error on the LMS.

```
django-tiers 0.2.1 requires django-model-utils<=2.3.1, but you'll have django-model-utils 3.2.0 which is incompatible.
```

See the [LMS pages show TypeError exception](https://appsembler.atlassian.net/wiki/spaces/BLA/pages/786366550/How+to+set+up+a+Tahoe+Devstack+using+Sultan#LMS-pages-show-TypeError-exception) error instructions.

**Comment by OmarIthawi** [comment]
Now pip gives me this on AMC `pip install -r requirements/base.txt`.
```
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.
We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.
django-tiers 0.2.1 requires django-model-utils<=2.3.1, but you'll have django-model-utils 3.2.0 which is incompatible. 
```

**Comment by thraxil** [comment]
I think the `django-models-utils<=2.3.1` constraint in `django-tiers` isn't necessary. It looks like it was added in the initial commit: https://github.com/appsembler/django-tiers/blame/master/setup.py#L26 and has never been updated. `django-tiers` only uses the `TimeStampedModel` from `django-model-utils` and that shouldn't require any kind of version restriction. I can only assume that the contstraint was originally placed as boilerplate.

**Comment by OmarIthawi** [comment]
Thanks @thraxil! I'll just remove the constraint then, it should fix this devstack issue.
